sudo: false
dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - '12'

branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)-dev$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION=1.25.5
  - MOZ_HEADLESS=1

before_install:
  # Login to NPM registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - npm ci
  - export CURRENT_VERSION=$(./scripts/get-release-version)
  # Install MN Bootstrap
  - export MN_RELEASE_LINK=$(./scripts/get-gh-release-link dashevo/mn-bootstrap)
  - curl -L $MN_RELEASE_LINK > mn-bootstrap.tar.gz
  - mkdir ~/mn-bootstrap && tar -C ~/mn-bootstrap -xvf mn-bootstrap.tar.gz
  - export MN_RELEASE_DIR="$(ls ~/mn-bootstrap)"
  - cd ~/mn-bootstrap/$MN_RELEASE_DIR
  - chmod -R 777 data
  - npm ci && npm link
  # Go back to workdir
  - cd -
  # Install DAPI
  - export DAPI_RELEASE_LINK=$(./scripts/get-gh-release-link dashevo/dapi)
  - curl -L $DAPI_RELEASE_LINK > dapi.tar.gz
  - mkdir ~/dapi && tar -C ~/dapi -xvf dapi.tar.gz
  - export DAPI_RELEASE_DIR="$(ls ~/dapi)"
  - cd ~/dapi/$DAPI_RELEASE_DIR
  - chmod -R 777 data
  # Go back to workdir
  - cd -
  # Install Drive
  - export DRIVE_RELEASE_LINK=$(./scripts/get-gh-release-link dashevo/drive
  - curl -L $DRIVE_RELEASE_LINK > drive.tar.gz
  - mkdir ~/drive && tar -C ~/drive -xvf drive.tar.gz
  - export DRIVE_RELEASE_DIR="$(ls ~/drive)"
  - cd ~/drive/$DRIVE_RELEASE_DIR
  - chmod -R 777 data
  # Go back to workdir
  - cd -

before_script:
  - export OUTPUT=$(mn setup-for-local-development 127.0.0.1 20001 --dapi-image-build-path=~/dapi/$DAPI_RELEASE_DIR --drive-image-build-path=~/drive/$DRIVE_RELEASE_DIR)
  - export PRIVATE_KEY=$(echo "$OUTPUT" | grep -m 1 "Private key:" | awk '{printf $4}')
  - export OPERATOR_BLS_KEY=$(echo "$OUTPUT" | grep -m 2 "Private key:" | tail -n 1 | awk '{printf $4}')
  - export DPNS_CONTRACT_ID=$(echo "$OUTPUT" | grep -m 1 "DPNS contract ID:" | awk '{printf $5}')
  - export DPNS_TOP_LEVEL_IDENTITY_ID=$(echo "$OUTPUT" | grep -m 1 "DPNS identity:" | awk '{printf $4}')
  - export DPNS_TOP_LEVEL_IDENTITY_PRIVATE_KEY=$(echo "$OUTPUT" | grep -m 1 "HD private key:" | awk '{$1=""; printf $5}')
  - mn start local 127.0.0.1 20001 -p=$OPERATOR_BLS_KEY --dpns-contract-id=$DPNS_CONTRACT_ID --dpns-top-level-identity=$DPNS_TOP_LEVEL_IDENTITY_ID --dapi-image-build-path=~/dapi/$DAPI_RELEASE_DIR --drive-image-build-path=~/drive/$DRIVE_RELEASE_DIR


script: >
  npm run check-package &&
  npm run lint &&
  npm run test &&
  docker run --network="host" -v $TRAVIS_BUILD_DIR:/node_modules/@dashevo/dpp dashpay/platform-test-suite:$CURRENT_VERSION 127.0.0.1:3000 -k=$PRIVATE_KEY -n=regtest --dpns-tld-identity-private-key=$DPNS_TOP_LEVEL_IDENTITY_PRIVATE_KEY --dpns-tld-identity-id=$DPNS_TOP_LEVEL_IDENTITY_ID --dpns-contract-id=$DPNS_CONTRACT_ID --scope=platform

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/js-dpp
      tags: true
